---
name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run YAML linter
        uses: ibm-cloud-security/secretsmanager-action@1.1.1
        with:
          command: lint
          files: .github/workflows/
